baseurl = "https://addzey.dev/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 8

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  enableGitInfo = true
  #showLastUpdated = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "ADDZEY.DEV"
    subtitle = "Adam's tech blog!"
    owner = "Adam Rogers"
    keywords = "blog cloud tech devops homelab selfhosting aws redhat"
    copyright = "Adam Rogers"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "ADDZEY.DEV"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 10
        identifier = "About"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        weight = 20
        identifier = "Homelab"
        name = "Homelab"
        url = "/homelab"
      [[languages.en.menu.main]]
        weight = 20
        identifier = "RHCSA"
        name = "RHCSA"
        url = "/rhcsa"
      [[languages.en.menu.main]]
        weight = 40
        identifier = "AWS SAA"
        name = "AWS SAA"
        url = "/aws-saa"
      [[languages.en.menu.main]]
        weight = 50
        identifier = "AWS DOP"
        name = "AWS DOP"
        url = "/aws-dop"
      [[languages.en.menu.main]]
        weight = 100
        pre = '<i class="fa-brands fa-github-square"></i>'
        identifier = "GitHub"
        name = "GitHub"
        url = "https://github.com/addzey"
      [[languages.en.menu.main]]
        weight = 110
        pre = '<i class="fa-brands fa-linkedin"></i>'
        identifier = "LinkedIn"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/adam-rogers-098466258/"